/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Minutes = IDL.Nat;
export const ClockTime = IDL.Text;
export const RoutePlan = IDL.Record({
  'originName' : IDL.Text,
  'walkingMinutes' : Minutes,
  'walkingSteps' : IDL.Vec(IDL.Text),
  'arriveBeforeClass' : IDL.Bool,
  'destinationName' : IDL.Text,
  'evSteps' : IDL.Vec(IDL.Text),
  'evMinutes' : Minutes,
  'estimatedArrival' : ClockTime,
  'totalMinutes' : Minutes,
  'finalWalkingMinutes' : Minutes,
});
export const AssistantAnswer = IDL.Record({
  'answer' : IDL.Text,
  'intent' : IDL.Text,
  'route' : IDL.Opt(RoutePlan),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Id = IDL.Nat;
export const CampusLocation = IDL.Record({
  'id' : Id,
  'kind' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const NextClass = IDL.Record({
  'startTime' : ClockTime,
  'subject' : IDL.Text,
  'endTime' : ClockTime,
  'minutesUntil' : Minutes,
  'locationName' : IDL.Text,
  'buildingName' : IDL.Text,
  'roomCode' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'studentId' : IDL.Text,
  'displayName' : IDL.Text,
  'year' : IDL.Nat,
  'avatarPlaceholder' : IDL.Text,
  'faculty' : IDL.Text,
});
export const SituationLevel = IDL.Variant({
  'A' : IDL.Null,
  'B' : IDL.Null,
  'C' : IDL.Null,
});
export const SmartMoment = IDL.Record({
  'startTime' : ClockTime,
  'originName' : IDL.Text,
  'subject' : IDL.Text,
  'walkingMinutes' : Minutes,
  'explanation' : IDL.Text,
  'situationMessage' : IDL.Text,
  'arriveBeforeClass' : IDL.Bool,
  'destinationName' : IDL.Text,
  'evMinutes' : Minutes,
  'buildingName' : IDL.Text,
  'roomCode' : IDL.Text,
  'minutesRemaining' : Minutes,
  'estimatedArrival' : ClockTime,
  'totalMinutes' : Minutes,
  'finalWalkingMinutes' : Minutes,
  'situation' : SituationLevel,
});
export const Building = IDL.Record({
  'id' : Id,
  'floors' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const EvLine = IDL.Record({
  'id' : Id,
  'nextStation' : IDL.Text,
  'name' : IDL.Text,
  'crowdLevel' : IDL.Text,
  'stops' : IDL.Vec(IDL.Text),
  'arrivalMinutes' : Minutes,
});
export const Room = IDL.Record({
  'id' : Id,
  'floor' : IDL.Nat,
  'code' : IDL.Text,
  'description' : IDL.Text,
  'buildingId' : Id,
  'buildingName' : IDL.Text,
});
export const Metres = IDL.Nat;
export const RouteSegment = IDL.Record({
  'walkingMinutes' : Minutes,
  'toLocationId' : Id,
  'fromLocationId' : Id,
  'instruction' : IDL.Text,
  'distanceMetres' : Metres,
});
export const DayOfWeek = IDL.Text;
export const ClassEntry = IDL.Record({
  'id' : Id,
  'day' : DayOfWeek,
  'startTime' : ClockTime,
  'subject' : IDL.Text,
  'endTime' : ClockTime,
  'instructor' : IDL.Text,
  'buildingName' : IDL.Text,
  'roomCode' : IDL.Text,
});
export const ScanResult = IDL.Record({
  'floor' : IDL.Nat,
  'instruction' : IDL.Text,
  'buildingName' : IDL.Text,
  'roomCode' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'askCampus' : IDL.Func([IDL.Text], [AssistantAnswer], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentLocation' : IDL.Func([], [CampusLocation], ['query']),
  'getNextClass' : IDL.Func([], [IDL.Opt(NextClass)], ['query']),
  'getProfile' : IDL.Func([], [StudentProfile], ['query']),
  'getSmartMoment' : IDL.Func([], [IDL.Opt(SmartMoment)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBuildings' : IDL.Func([], [IDL.Vec(Building)], ['query']),
  'listEvLines' : IDL.Func([], [IDL.Vec(EvLine)], ['query']),
  'listLocations' : IDL.Func([], [IDL.Vec(CampusLocation)], ['query']),
  'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'listRouteSegments' : IDL.Func([], [IDL.Vec(RouteSegment)], ['query']),
  'listSchedule' : IDL.Func([], [IDL.Vec(ClassEntry)], ['query']),
  'planRoute' : IDL.Func([IDL.Text, IDL.Text], [RoutePlan], ['query']),
  'scan' : IDL.Func([], [ScanResult], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Minutes = IDL.Nat;
  const ClockTime = IDL.Text;
  const RoutePlan = IDL.Record({
    'originName' : IDL.Text,
    'walkingMinutes' : Minutes,
    'walkingSteps' : IDL.Vec(IDL.Text),
    'arriveBeforeClass' : IDL.Bool,
    'destinationName' : IDL.Text,
    'evSteps' : IDL.Vec(IDL.Text),
    'evMinutes' : Minutes,
    'estimatedArrival' : ClockTime,
    'totalMinutes' : Minutes,
    'finalWalkingMinutes' : Minutes,
  });
  const AssistantAnswer = IDL.Record({
    'answer' : IDL.Text,
    'intent' : IDL.Text,
    'route' : IDL.Opt(RoutePlan),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Id = IDL.Nat;
  const CampusLocation = IDL.Record({
    'id' : Id,
    'kind' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const NextClass = IDL.Record({
    'startTime' : ClockTime,
    'subject' : IDL.Text,
    'endTime' : ClockTime,
    'minutesUntil' : Minutes,
    'locationName' : IDL.Text,
    'buildingName' : IDL.Text,
    'roomCode' : IDL.Text,
  });
  const StudentProfile = IDL.Record({
    'studentId' : IDL.Text,
    'displayName' : IDL.Text,
    'year' : IDL.Nat,
    'avatarPlaceholder' : IDL.Text,
    'faculty' : IDL.Text,
  });
  const SituationLevel = IDL.Variant({
    'A' : IDL.Null,
    'B' : IDL.Null,
    'C' : IDL.Null,
  });
  const SmartMoment = IDL.Record({
    'startTime' : ClockTime,
    'originName' : IDL.Text,
    'subject' : IDL.Text,
    'walkingMinutes' : Minutes,
    'explanation' : IDL.Text,
    'situationMessage' : IDL.Text,
    'arriveBeforeClass' : IDL.Bool,
    'destinationName' : IDL.Text,
    'evMinutes' : Minutes,
    'buildingName' : IDL.Text,
    'roomCode' : IDL.Text,
    'minutesRemaining' : Minutes,
    'estimatedArrival' : ClockTime,
    'totalMinutes' : Minutes,
    'finalWalkingMinutes' : Minutes,
    'situation' : SituationLevel,
  });
  const Building = IDL.Record({
    'id' : Id,
    'floors' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const EvLine = IDL.Record({
    'id' : Id,
    'nextStation' : IDL.Text,
    'name' : IDL.Text,
    'crowdLevel' : IDL.Text,
    'stops' : IDL.Vec(IDL.Text),
    'arrivalMinutes' : Minutes,
  });
  const Room = IDL.Record({
    'id' : Id,
    'floor' : IDL.Nat,
    'code' : IDL.Text,
    'description' : IDL.Text,
    'buildingId' : Id,
    'buildingName' : IDL.Text,
  });
  const Metres = IDL.Nat;
  const RouteSegment = IDL.Record({
    'walkingMinutes' : Minutes,
    'toLocationId' : Id,
    'fromLocationId' : Id,
    'instruction' : IDL.Text,
    'distanceMetres' : Metres,
  });
  const DayOfWeek = IDL.Text;
  const ClassEntry = IDL.Record({
    'id' : Id,
    'day' : DayOfWeek,
    'startTime' : ClockTime,
    'subject' : IDL.Text,
    'endTime' : ClockTime,
    'instructor' : IDL.Text,
    'buildingName' : IDL.Text,
    'roomCode' : IDL.Text,
  });
  const ScanResult = IDL.Record({
    'floor' : IDL.Nat,
    'instruction' : IDL.Text,
    'buildingName' : IDL.Text,
    'roomCode' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'askCampus' : IDL.Func([IDL.Text], [AssistantAnswer], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentLocation' : IDL.Func([], [CampusLocation], ['query']),
    'getNextClass' : IDL.Func([], [IDL.Opt(NextClass)], ['query']),
    'getProfile' : IDL.Func([], [StudentProfile], ['query']),
    'getSmartMoment' : IDL.Func([], [IDL.Opt(SmartMoment)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBuildings' : IDL.Func([], [IDL.Vec(Building)], ['query']),
    'listEvLines' : IDL.Func([], [IDL.Vec(EvLine)], ['query']),
    'listLocations' : IDL.Func([], [IDL.Vec(CampusLocation)], ['query']),
    'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'listRouteSegments' : IDL.Func([], [IDL.Vec(RouteSegment)], ['query']),
    'listSchedule' : IDL.Func([], [IDL.Vec(ClassEntry)], ['query']),
    'planRoute' : IDL.Func([IDL.Text, IDL.Text], [RoutePlan], ['query']),
    'scan' : IDL.Func([], [ScanResult], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };