/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssistantAnswer {
  'answer' : string,
  'intent' : string,
  'route' : [] | [RoutePlan],
}
export interface Building {
  'id' : Id,
  'floors' : bigint,
  'code' : string,
  'name' : string,
  'description' : string,
}
export interface CampusLocation {
  'id' : Id,
  'kind' : string,
  'name' : string,
  'description' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ClassEntry {
  'id' : Id,
  'day' : DayOfWeek,
  'startTime' : ClockTime,
  'subject' : string,
  'endTime' : ClockTime,
  'instructor' : string,
  'buildingName' : string,
  'roomCode' : string,
}
export type ClockTime = string;
export type DayOfWeek = string;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface EvLine {
  'id' : Id,
  'nextStation' : string,
  'name' : string,
  'crowdLevel' : string,
  'stops' : Array<string>,
  'arrivalMinutes' : Minutes,
}
export type Id = bigint;
export type Metres = bigint;
export type Minutes = bigint;
export interface NextClass {
  'startTime' : ClockTime,
  'subject' : string,
  'endTime' : ClockTime,
  'minutesUntil' : Minutes,
  'locationName' : string,
  'buildingName' : string,
  'roomCode' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Room {
  'id' : Id,
  'floor' : bigint,
  'code' : string,
  'description' : string,
  'buildingId' : Id,
  'buildingName' : string,
}
export interface RoutePlan {
  'originName' : string,
  'walkingMinutes' : Minutes,
  'walkingSteps' : Array<string>,
  'arriveBeforeClass' : boolean,
  'destinationName' : string,
  'evSteps' : Array<string>,
  'evMinutes' : Minutes,
  'estimatedArrival' : ClockTime,
  'totalMinutes' : Minutes,
  'finalWalkingMinutes' : Minutes,
}
export interface RouteSegment {
  'walkingMinutes' : Minutes,
  'toLocationId' : Id,
  'fromLocationId' : Id,
  'instruction' : string,
  'distanceMetres' : Metres,
}
export interface ScanResult {
  'floor' : bigint,
  'instruction' : string,
  'buildingName' : string,
  'roomCode' : string,
}
export type SituationLevel = { 'A' : null } |
  { 'B' : null } |
  { 'C' : null };
export interface SmartMoment {
  'startTime' : ClockTime,
  'originName' : string,
  'subject' : string,
  'walkingMinutes' : Minutes,
  'explanation' : string,
  'situationMessage' : string,
  'arriveBeforeClass' : boolean,
  'destinationName' : string,
  'evMinutes' : Minutes,
  'buildingName' : string,
  'roomCode' : string,
  'minutesRemaining' : Minutes,
  'estimatedArrival' : ClockTime,
  'totalMinutes' : Minutes,
  'finalWalkingMinutes' : Minutes,
  'situation' : SituationLevel,
}
export interface StudentProfile {
  'studentId' : string,
  'displayName' : string,
  'year' : bigint,
  'avatarPlaceholder' : string,
  'faculty' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'askCampus' : ActorMethod<[string], AssistantAnswer>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentLocation' : ActorMethod<[], CampusLocation>,
  'getNextClass' : ActorMethod<[], [] | [NextClass]>,
  'getProfile' : ActorMethod<[], StudentProfile>,
  'getSmartMoment' : ActorMethod<[], [] | [SmartMoment]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBuildings' : ActorMethod<[], Array<Building>>,
  'listEvLines' : ActorMethod<[], Array<EvLine>>,
  'listLocations' : ActorMethod<[], Array<CampusLocation>>,
  'listRooms' : ActorMethod<[], Array<Room>>,
  'listRouteSegments' : ActorMethod<[], Array<RouteSegment>>,
  'listSchedule' : ActorMethod<[], Array<ClassEntry>>,
  'planRoute' : ActorMethod<[string, string], RoutePlan>,
  'scan' : ActorMethod<[], ScanResult>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];